/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as ExpeditionsIndexRouteImport } from './routes/expeditions.index'
import { Route as ExpeditionsSlugRouteImport } from './routes/expeditions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsIndexRoute = ExpeditionsIndexRouteImport.update({
  id: '/expeditions/',
  path: '/expeditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsSlugRoute = ExpeditionsSlugRouteImport.update({
  id: '/expeditions/$slug',
  path: '/expeditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/repository': typeof RepositoryRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/repository': typeof RepositoryRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/expeditions': typeof ExpeditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outreach': typeof OutreachRoute
  '/repository': typeof RepositoryRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/login'
    | '/media'
    | '/outreach'
    | '/repository'
    | '/expeditions/$slug'
    | '/expeditions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/login'
    | '/media'
    | '/outreach'
    | '/repository'
    | '/expeditions/$slug'
    | '/expeditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/login'
    | '/media'
    | '/outreach'
    | '/repository'
    | '/expeditions/$slug'
    | '/expeditions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OutreachRoute: typeof OutreachRoute
  RepositoryRoute: typeof RepositoryRoute
  ExpeditionsSlugRoute: typeof ExpeditionsSlugRoute
  ExpeditionsIndexRoute: typeof ExpeditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/': {
      id: '/expeditions/'
      path: '/expeditions'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof ExpeditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/$slug': {
      id: '/expeditions/$slug'
      path: '/expeditions/$slug'
      fullPath: '/expeditions/$slug'
      preLoaderRoute: typeof ExpeditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OutreachRoute: OutreachRoute,
  RepositoryRoute: RepositoryRoute,
  ExpeditionsSlugRoute: ExpeditionsSlugRoute,
  ExpeditionsIndexRoute: ExpeditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
