-- Extend the public archive with seven additional campaigns and their linked records.
INSERT INTO public.expeditions (slug, name, code, region, year, start_date, end_date, platform, themes, summary, leader, team_size, highlights, route_stops, image_key) VALUES
('isea-2026-antarctic-44','44th Indian Scientific Expedition to Antarctica','ISEA-44','Antarctic',2026,'2025-11-08','2026-04-12','Maitri & Bharati Stations','{"Cryosphere","Coastal Oceanography","Polar Engineering"}','A full summer and winter-over season focused on ice-shelf stability, coastal ocean observations and resilient station systems across the Indian Antarctic programme.','Dr. Ananya Rao',74,'{"Autonomous ocean mooring installed off the Larsemann coast","New snow-radar transects completed across Schirmacher Oasis","Station microgrid control system commissioned"}','[{"name":"Cape Town","note":"Cargo staging and personnel transfer"},{"name":"Maitri Station","note":"Ice and engineering programme"},{"name":"Larsemann Hills","note":"Coastal ocean mooring deployment"},{"name":"Bharati Station","note":"Marine and atmosphere observations"}]','ice-shelf'),
('iare-2026-arctic-spring','Indian Arctic Expedition — Spring Campaign 2026','IARE-2026SP','Arctic',2026,'2026-03-18','2026-06-10','Himadri Station, Ny-Ålesund','{"Snow Science","Atmospheric Science","Fjord Ecology"}','Spring observations at Himadri examine snow-albedo change, Arctic haze transport and the seasonal awakening of Kongsfjorden ecosystems.','Dr. Ritu Menon',20,'{"Daily snow albedo transect established","Arctic haze event sampled from surface to Zeppelin ridge","First spring plankton bloom profiles collected"}','[{"name":"Longyearbyen","note":"Arctic logistics hub"},{"name":"Ny-Ålesund","note":"Himadri Station base"},{"name":"Zeppelin Ridge","note":"Atmospheric sampling"},{"name":"Kongsfjorden","note":"Spring ecosystem survey"}]','arctic-fjord'),
('sore-2025-09','Southern Ocean Research Expedition — Leg 9','SORE-09','Southern Ocean',2025,'2025-12-12','2026-03-30','ORV Sagar Nidhi','{"Oceanography","Marine Biogeochemistry","Climate"}','Leg 9 followed a repeat meridional transect to investigate carbon uptake, ocean heat storage and changing plankton communities south of 55 degrees.','Dr. Meera Krishnan',44,'{"Fifty-two hydrographic stations occupied","Three biogeochemical floats deployed","High-resolution carbon uptake section completed"}','[{"name":"Chennai","note":"Mobilisation and departure"},{"name":"Subantarctic Zone","note":"Carbon and plankton survey"},{"name":"Polar Front","note":"Repeat hydrography"},{"name":"Prydz Bay","note":"Southern station occupation"}]','southern-ocean'),
('himansh-2026','Himansh Glacier Observatory Campaign 2026','HIM-2026','Himalaya',2026,'2026-05-10','2026-10-18','Himansh Station, Chandra Basin','{"Glaciology","Hydrology","Climate Adaptation"}','A high-altitude campaign combining glacier mass balance measurements with downstream water-security studies and community climate observations.','Dr. Kabir Nandy',21,'{"Winter snow accumulation mapped on nine glaciers","New meltwater gauges added to the Chandra basin","Community water diaries launched in three villages"}','[{"name":"Manali","note":"Acclimatisation and equipment checks"},{"name":"Himansh Station","note":"Observatory base"},{"name":"Bara Shigri Glacier","note":"Mass balance survey"},{"name":"Chandra Valley","note":"Water-security fieldwork"}]','himalaya'),
('isea-2022-antarctic-40','40th Indian Scientific Expedition to Antarctica','ISEA-40','Antarctic',2022,'2021-11-16','2022-03-28','Maitri & Bharati Stations','{"Geology","Meteorology","Polar Biology"}','The fortieth Antarctic season combined station resupply with long-term meteorological records, geology traverses and coastal wildlife monitoring.','Dr. Sunita Bhalla',59,'{"Twenty-year meteorology record consolidated","New geology transect completed near Wohlthat Mountains","Weddell seal observation programme expanded"}','[{"name":"Cape Town","note":"Staging and embarkation"},{"name":"Maitri Station","note":"Meteorology and geology operations"},{"name":"Wohlthat Mountains","note":"Geological traverse"},{"name":"Bharati Station","note":"Coastal biology surveys"}]','station-night'),
('iare-2023-arctic-autumn','Indian Arctic Expedition — Autumn Campaign 2023','IARE-2023A','Arctic',2023,'2023-08-19','2023-10-04','Himadri Station, Ny-Ålesund','{"Permafrost","Atmospheric Science","Sea Ice"}','An autumn transition campaign documenting permafrost freeze-back, boundary-layer chemistry and early sea-ice formation in the Svalbard archipelago.','Dr. Vikram Shetty',16,'{"Permafrost borehole network serviced before winter","Autumn aerosol composition record completed","Sea-ice formation observed at twelve fjord sites"}','[{"name":"Longyearbyen","note":"Arrival and field mobilisation"},{"name":"Ny-Ålesund","note":"Station operations"},{"name":"Brøgger Peninsula","note":"Permafrost boreholes"},{"name":"Kongsfjorden","note":"Sea-ice monitoring"}]','aurora'),
('sore-2022-06','Southern Ocean Research Expedition — Leg 6','SORE-06','Southern Ocean',2022,'2022-01-11','2022-03-14','ORV Sagar Kanya','{"Oceanography","Marine Biology","Atmospheric Science"}','The sixth Southern Ocean leg built a baseline for ocean acidification, phytoplankton diversity and marine aerosol measurements across the Indian sector.','Dr. Meera Krishnan',36,'{"First regional ocean acidification baseline assembled","DNA samples collected from 34 plankton stations","Marine aerosol filter archive established"}','[{"name":"Port Louis","note":"Vessel mobilisation"},{"name":"Subtropical Front","note":"Baseline stations"},{"name":"Polar Front","note":"Plankton and aerosol survey"},{"name":"Antarctic Circumpolar Current","note":"Southernmost transect"}]','ship-deck');

INSERT INTO public.repository_items (title, item_type, year, theme, authors, abstract, reference, file_format, file_size, expedition_slug) VALUES
('ISEA-44 Antarctic Coastal Observations Dataset','dataset',2026,'Coastal Oceanography','Rao A., Joseph L.','Temperature, salinity and current observations from the new Larsemann coast mooring during the 2025-26 season.','SIH/DAT/2026/004','NetCDF','680 MB','isea-2026-antarctic-44'),
('IARE Spring 2026 Snow and Haze Report','report',2026,'Atmospheric Science','Menon R.','Field report linking spring snow reflectance observations with Arctic haze transport episodes around Ny-Ålesund.','SIH/REP/2026/009','PDF','10.6 MB','iare-2026-arctic-spring'),
('SORE-09 Carbon Uptake Section','dataset',2025,'Marine Biogeochemistry','Krishnan M., Varma T.','Calibrated underway carbon and hydrographic observations from the Leg 9 meridional section.','SIH/DAT/2025/038','CSV','315 MB','sore-2025-09'),
('Himansh 2026 Water Security Field Notes','report',2026,'Climate Adaptation','Nandy K., Sharma R.','Integrated glacier and community water observations from the Chandra basin summer campaign.','SIH/REP/2026/012','PDF','8.1 MB','himansh-2026'),
('ISEA-40 Meteorological Record 2002-2022','dataset',2022,'Meteorology','Bhalla S.','Quality-controlled daily station observations compiled during the fortieth Antarctic expedition.','SIH/DAT/2022/017','CSV','96 MB','isea-2022-antarctic-40'),
('Autumn Permafrost Freeze-back at Ny-Ålesund','publication',2023,'Permafrost','Shetty V., Menon R.','Borehole observations quantify the timing and depth of freeze-back across contrasting Arctic surface types.','Arctic Cryosphere 14(2), 75-93','PDF','5.8 MB','iare-2023-arctic-autumn'),
('SORE-06 Ocean Acidification Baseline','dataset',2022,'Oceanography','Krishnan M., Joseph L.','Carbonate chemistry observations providing a regional baseline for the Indian sector of the Southern Ocean.','SIH/DAT/2022/006','NetCDF','430 MB','sore-2022-06');

INSERT INTO public.media_items (title, kind, caption, credit, theme, captured_on, duration, image_key, expedition_slug) VALUES
('Maitri microgrid installation','photo','Engineers connect the new control system during the 44th Antarctic season.','SIH Photo Unit','Polar Engineering','2026-01-18',NULL,'ice-shelf','isea-2026-antarctic-44'),
('Spring light over Kongsfjorden','photo','A sampling team prepares for the first fjord profile of the Arctic spring.','SIH Photo Unit','Fjord Ecology','2026-04-22',NULL,'arctic-fjord','iare-2026-arctic-spring'),
('Leg 9 carbon sampling','photo','Deck team prepares the underway carbon analyser during a Southern Ocean transit.','SIH Photo Unit','Marine Biogeochemistry','2026-02-06',NULL,'ship-deck','sore-2025-09'),
('Bara Shigri snow survey','photo','The Himansh team measures late-season snow depth on a benchmark glacier.','SIH Photo Unit','Glaciology','2026-08-12',NULL,'himalaya','himansh-2026'),
('Wohlthat Mountains traverse','photo','Geologists document exposed rock units during the fortieth Antarctic season.','SIH Photo Unit','Geology','2022-01-29',NULL,'station-night','isea-2022-antarctic-40'),
('Autumn sea ice at Kongsfjorden','photo','Thin new ice forms along the fjord edge near Ny-Ålesund.','SIH Photo Unit','Sea Ice','2023-09-21',NULL,'aurora','iare-2023-arctic-autumn'),
('SORE-06 plankton tow','video','A short field film following the plankton and aerosol teams during Leg 6.','SIH Media Cell','Marine Biology','2022-04-09','07:18','southern-ocean','sore-2022-06');

INSERT INTO public.activities (title, activity_type, starts_on, ends_on, location, audience, description) VALUES
('Antarctic Field Systems Open Day','Outreach programme','2026-10-16',NULL,'Goa and online','Students, families','Hands-on demonstrations of Antarctic station engineering and live discussions with ISEA-44 field teams.'),
('Arctic Spring Science Seminar','Seminar','2026-10-28',NULL,'Online','Researchers, students','Researchers present early findings on spring Arctic haze, snow reflectance and fjord ecosystems.'),
('Southern Ocean Data Release Clinic','Workshop','2026-11-11','2026-11-12','Goa','Early career researchers','Practical sessions for using the new Leg 9 carbon and hydrography records.'),
('Himalayan Water Futures Dialogue','Public forum','2026-11-25',NULL,'Manali','Communities, policy makers','A conversation on glacier observations, water security and locally useful climate information.'),
('Antarctic Meteorology Archive Launch','Archive event','2026-12-03',NULL,'Online','General public','Public release of the consolidated ISEA-40 meteorological archive and explainer materials.'),
('Arctic Permafrost Methods Masterclass','Training','2027-01-14','2027-01-15','Online','Researchers','Training on borehole observations, seasonal frost analysis and reproducible Arctic data workflows.'),
('Southern Ocean Film Evening','Exhibition','2027-02-06',NULL,'Chennai','General public','Screening of field films from SORE-06 and SORE-09 with an oceanographer-led discussion.');
